/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as ProtectedIndexRouteImport } from "./routes/_protected/index";
import { Route as ProtectedNewRouteImport } from "./routes/_protected/new";
import { Route as ProtectedTodoIdEditRouteImport } from "./routes/_protected/$todoId/edit";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedNewRoute = ProtectedNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedTodoIdEditRoute = ProtectedTodoIdEditRouteImport.update({
  id: "/$todoId/edit",
  path: "/$todoId/edit",
  getParentRoute: () => ProtectedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof ProtectedIndexRoute;
  "/login": typeof LoginRoute;
  "/new": typeof ProtectedNewRoute;
  "/$todoId/edit": typeof ProtectedTodoIdEditRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/new": typeof ProtectedNewRoute;
  "/": typeof ProtectedIndexRoute;
  "/$todoId/edit": typeof ProtectedTodoIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_protected/new": typeof ProtectedNewRoute;
  "/_protected/": typeof ProtectedIndexRoute;
  "/_protected/$todoId/edit": typeof ProtectedTodoIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/new" | "/$todoId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/new" | "/" | "/$todoId/edit";
  id:
    | "__root__"
    | "/_protected"
    | "/login"
    | "/_protected/new"
    | "/_protected/"
    | "/_protected/$todoId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/": {
      id: "/_protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/new": {
      id: "/_protected/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof ProtectedNewRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_protected/$todoId/edit": {
      id: "/_protected/$todoId/edit";
      path: "/$todoId/edit";
      fullPath: "/$todoId/edit";
      preLoaderRoute: typeof ProtectedTodoIdEditRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface ProtectedRouteChildren {
  ProtectedNewRoute: typeof ProtectedNewRoute;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
  ProtectedTodoIdEditRoute: typeof ProtectedTodoIdEditRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedNewRoute: ProtectedNewRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTodoIdEditRoute: ProtectedTodoIdEditRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(ProtectedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
